### PR TITLE
Add a link to Twi project

### PR DESCRIPTION
**Pull request by octet-stream**
I've also added a new section, named "CMS", if you don't mind.
~~But I'm don't actually sure is that a good name for this section, because Twi is just an engine and still on early stage of development cycle.~~

### CODE REVIEW

**Comment by ngyikp** [comment]
Is Twi going to be (1) primarily a hosted website like Pony.fm or (2) a general-purpose engine like WordPress/phpBB?

If (1), you could just put it into the "Website platforms" section.

**Comment by octet-stream** [comment]
Twi will be more like general-purpose engine, but oriented on fanfiction libraries.
And maybe I'll host a playground with demo and docs.

**Comment by ngyikp** [comment]
Hmm... I think putting it at the Misc section should be fine for now, no need for a separate CMS section unless we suddenly get 5 more CMS for some reason.

I'll do the adjustment and merge it in.

**Comment by octet-stream** [comment]
Sounds good. Thank you.

**Pull request merged**
